[CAZB-7455] Back buttons showing incorrect VRN
InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web pull request #1086
Opened 2022-09-07 02:58 UTC by arctindev

https://informedsolutions.atlassian.net/browse/CAZB-7455

## Motivation and Context

## Description

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] It contains only changes required by issue (does not contain other PR)
- [ ] Includes link to an issue (if apply)
- [ ] I have added tests to cover my changes.

2022-09-07 07:40 UTC, likeuwill requested changes
Please add spec for concert. Also, we need to think about max size for history, atm u wrote 9 steps, maybe we don't need so much.

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
> +  include VrnSession
```suggestion
  include VrnSessionManipulator
```
Would give us more info about what going on in concern

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
> +  end
same method used in two places, no need

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
> +  before_action :compliance_back_button_check, only: %i[compliance non_uk_compliance]
just move the logic into concern, for e.g.
```
  def update_current_vrn_index
    return unless session[:last_page_visited] == enter_details_vehicle_checkers_path
      
    session[:current_vrn_index] = session[:current_vrn_index] - 1
  end
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
> +  # Disable default browser caching.
no need to describe before_action, methods already described, we just generate unused /duplicated comments.

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/application_controller.rb
> +  def last_page_visited
```suggestion
  def assign_last_page_visited
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/concerns/vrn_session.rb
> +    session[:vrn][session[:current_vrn_index].to_i] = vrn
Should work
```suggestion
    session[:vrn] ||= []
    session[:vrn][session[:current_vrn_index].to_i] = vrn
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/concerns/vrn_session.rb
> +  def vrn_session_new_search
```suggestion
  def update_current_vrn_index
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/concerns/vrn_session.rb
> +  def vrn_session_replace_current(vrn)
```suggestion
  def replace_current_vrn_index(vrn)
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/concerns/vrn_session.rb
> +  def vrn_session_add_vrn(vrn)
```suggestion
  def add_current_vrn(vrn)
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/concerns/vrn_session.rb
> +  def vrn_session_clear
```suggestion
  def clear_session
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/vehicle_checkers_controller.rb
> +  before_action :set_cache_headers,
please remove comments

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/vehicle_checkers_controller.rb
> +  def enter_details_back_button_check # rubocop:disable Metrics/AbcSize
```suggestion
  def back_button_used
```

2022-09-07 07:40 UTC, likeuwill commented on app/controllers/vehicle_checkers_controller.rb
> +      session[:last_page_visited] == number_not_found_vehicle_checkers_path
Can we use case statement ?

2022-09-09 06:29 UTC, wojw5 commented
Looks good to me, but I don't want to approve/reject it just because I don't know the context of how it was built elsewhere. Can spend more time digging into details if you would like to.

2022-09-12 17:06 UTC, arctindev commented on app/controllers/air_zones_controller.rb
> +  before_action :compliance_back_button_check, only: %i[compliance non_uk_compliance]
This check is needed before :check_vrn, otherwise check_vrn will search for vrn before the index was changed

2022-09-13 07:21 UTC, likeuwill approved these changes

2022-09-13 07:22 UTC, merged