[CAZB-5826] Link between VCCS and Payments
InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web pull request #890
Opened 2021-12-23 15:05 UTC by arctindev

## Motivation and Context

https://eaflood.atlassian.net/browse/CAZB-5826

## Description

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] It contains only changes required by issue (does not contain other PR)
- [ ] Includes link to an issue (if apply)
- [ ] I have added tests to cover my changes.

2021-12-23 18:42 UTC, likeuwill requested changes
Keep in mind, rspec tests should pass without any env variables in `.env` file. Test should be green with empty .env in ideal world of course :)

2021-12-23 18:42 UTC, likeuwill commented on .env.example
> +# Secret manager variables
We need more context here, maybe better will be `AWS Secrets Manager credentials`

2021-12-23 18:42 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +
add module description

2021-12-23 18:42 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
> +  before_action :encrypt_vrn
You need to encrypt vrn only on compliance page

2021-12-23 18:42 UTC, likeuwill commented on app/services/secrets/connection.rb
> +    def connect_to_sm
method description

2021-12-23 18:42 UTC, likeuwill commented on app/services/secrets/connection.rb
> +        region: ENV['AWS_REGION'],
```
      Aws::SecretsManager::Client.new(
        region: ENV['AWS_REGION'],
        credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY']
        )
      )
```

2021-12-23 18:42 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +    end
Use private block and remove unnecessary code.

2021-12-23 18:45 UTC, likeuwill commented
Can be helpful in case when tests failing with empty values. Use fetch method
```
ENV.fetch('AWS_ACCESS_KEY_ID', 'AWS_ACCESS_KEY_ID')
```

2021-12-24 15:36 UTC, likeuwill requested changes

2021-12-24 15:36 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
> +    @encrypted_vrn = Secrets::VrnEncryption.new.encrypt_vrn(vrn)
```suggestion
    @encrypted_vrn = Secrets::VrnEncryption.call(vrn: vrn)
```

2021-12-24 15:36 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +  end
I added default values, because can't even run the server without them. Also refactored a bit. Looking in to https://ruby-doc.org/stdlib-3.0.2/libdoc/openssl/rdoc/OpenSSL/Cipher.html they using uppercase format, so i think better to be on same line with ruby docs :)

```
  # Encryption class for vrns
  class VrnEncryption < Connection
    ##
    # Initializer method.
    #
    # ==== Attributes
    # * +vrn+ - string, eg. 'CU57ABC'
    #
    def initialize(vrn:)
      @vrn = vrn
    end

    # Encrypting vrn
    def call
      cipher = OpenSSL::Cipher.new('AES-128-CBC').encrypt
      cipher_keys(cipher)
      Base64.urlsafe_encode64(cipher.update(vrn) + cipher.final)
    end

    private

    attr_reader :vrn

    def cipher_keys(cipher)
      cipher.key = Base64.decode64(secret_manager_credentials['ENCRYPTION_KEY'])
      cipher.iv = Base64.decode64(secret_manager_credentials['INITIALISATION_VECTOR'])
    end

    def secret_manager_credentials
      secret_name = ENV.fetch('VRN_ENCRYPTION_SECRET', 'VRN_ENCRYPTION_SECRET')
      JSON.parse(connect_to_sm.get_secret_value(secret_id: secret_name).secret_string)
    end
  end
```

2021-12-24 15:36 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +  end
Add to rubocop ignore list 
```
Lint/MissingSuper:
  Enabled: false
```

2021-12-24 15:36 UTC, likeuwill commented on app/services/secrets/connection.rb
> +    end
```
    def connect_to_sm
      Aws::SecretsManager::Client.new(
        region: ENV.fetch('AWS_REGION', 'eu-west-2'),
        credentials: Aws::Credentials.new(
          ENV.fetch('AWS_ACCESS_KEY_ID', 'AWS_ACCESS_KEY_ID'),
          ENV.fetch('AWS_SECRET_ACCESS_KEY', 'AWS_SECRET_ACCESS_KEY')
        )
      )
    end
```

2021-12-24 15:51 UTC, likeuwill commented on app/services/secrets/connection.rb
> +    end
Also, maybe we need to add `aws_secret_manager_client.rb` to initializers because without it we will not be able(role permissions) to fetch credentials from AWS SM. Would be nice for you to create on your private account, same credentials and test.

But we can test it after dev ops task will be done. Because now i have `Aws::SecretsManager::Errors::AccessDeniedException` error.  If u change this code `JSON.parse(AWS_SM_CLIENT.get_secret_value(secret_id: secret_name).secret_string)`
```
# frozen_string_literal: true

is_running_locally = Rails.env.development?
is_running_on_aws = Rails.env.production? && ENV['BUILD_ID']

# Development environment config
access_key_id = ENV['AWS_ACCESS_KEY_ID']
secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
assume_role_arn = ENV['AWS_ROLE_ARN']
assume_role_session_name = 'jaqu-lowerDeveloperRole-localdev'

# Production environment config
task_metadata_address = '169.254.170.2'

# Common environment config
region = ENV.fetch('AWS_REGION', 'eu-west-2')

credentials = if is_running_locally
                # On local machines we are using STS
                Aws::AssumeRoleCredentials.new(
                  client: Aws::STS::Client.new(
                    region: region,
                    access_key_id: access_key_id,
                    secret_access_key: secret_access_key
                  ),
                  role_arn: assume_role_arn,
                  role_session_name: assume_role_session_name
                )
              elsif is_running_on_aws
                # On AWS ECS we are using task credentials
                Aws::ECSCredentials.new({ ip_address: task_metadata_address })
              else
                # In tests and Docker build we are using regular credentials
                Aws::Credentials.new(access_key_id, secret_access_key)
              end

AWS_SM_CLIENT = Aws::SecretsManager::Client.new(
  region: region,
  credentials: credentials
)
```

2021-12-27 12:12 UTC, likeuwill requested changes
CR

2021-12-27 16:16 UTC, likeuwill requested changes

2021-12-27 16:16 UTC, likeuwill commented on app/controllers/air_zones_controller.rb
>    before_action :check_vrn
```suggestion
  before_action :check_vrn
  before_action :encrypt_vrn, only: :compliance
```
global methods should be always first, both cases will work properly, but logic should same as methods execution.

2021-12-27 16:16 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +    def initialize(vrn:) # rubocop:disable Lint/MissingSuper
add this rule to global config, as we have in another projects

2021-12-27 16:16 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +    # Gets cipher key and iv
```suggestion
    # Gets cipher key and iv from AWS SM and assign it to cipher
```

2021-12-27 16:16 UTC, likeuwill commented on .env.example
> +# AWS Secrets Manager credentials
Looking into https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SecretsManager/Client.html
`:secret_id (required, String) — Specifies the secret containing the version that you want to retrieve. You can specify either the Amazon Resource Name (ARN) or the friendly name of the secret.
`
Let's describe it, e.g., `Secrete name used to retrieve the secret string value from AWS Secretes manager`

```
# The following example shows how to retrieve the secret string value from the version of the secret that has the AWSPREVIOUS staging label attached. If you want to retrieve the AWSCURRENT version of the secret, then you can omit the VersionStage parameter because it defaults to AWSCURRENT.

resp = client.get_secret_value({
  secret_id: "MyTestDatabaseSecret", 
  version_stage: "AWSPREVIOUS", 
})

# resp.to_h outputs the following:
{
  arn: "arn:aws:secretsmanager:us-west-2:123456789012:secret:MyTestDatabaseSecret-a1b2c3", 
  created_date: Time.parse(1523477145.713), 
  name: "MyTestDatabaseSecret", 
  secret_string: "{\n  \"username\":\"david\",\n  \"password\":\"BnQw&XDWgaEeT9XGTT29\"\n}\n", 
  version_id: "EXAMPLE1-90ab-cdef-fedc-ba987SECRET1", 
  version_stages: [
    "AWSPREVIOUS", 
  ], 
}
```
Also dont we need `.to_` method to get values? Just asking because in example they used `to_h`. Can u test in on your private account?

2021-12-28 10:18 UTC, likeuwill requested changes

2021-12-28 10:18 UTC, likeuwill commented on app/services/secrets/vrn_encryption.rb
> +# Module used to encrypt vrn
remove it plz

2021-12-28 10:18 UTC, likeuwill commented on .env.example
> +# AWS Secrets Manager credentials
`Secrete name used to retrieve the secret string value from AWS Secretes manager`

2021-12-30 09:13 UTC, dratka approved these changes

2021-12-30 10:02 UTC, likeuwill approved these changes

2021-12-30 10:02 UTC, merged